# docker-compose.yml

services:
  # PHP Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auren_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - auren-network
    depends_on:
      - db


  # Nginx Web Server Service
  nginx:
    image: nginx:1.25-alpine
    container_name: auren_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auren-network
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: auren_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - auren-network

# Docker Networks
networks:
  auren-network:
    driver: bridge